#!/usr/bin/env ruby

require_relative './helper'
include ExecutableHelper

require 'ebay_trading'
require 'ebay_trading/request'

begin

  # GeteBayOfficialTime call is not specific to any particular user, so can
  # use any valid Auth Token.
  auth_token = production_auth_tokens.values.first

  # Execute the request...
  request = EbayTrading::Request.new('GeteBayOfficialTime', auth_token)

  if request.success?
    console "Official eBay time is:  #{request.timestamp.to_s('%H:%M:%S GMT on %A %d %B %Y')}"
  else
    if request.has_errors?
      request.errors.each do |error|
        console error[:short_message], :red
        console error[:long_message], :red
      end
    else
      console 'Unknown error', :red
    end
  end
rescue Exception => e
  console e.message, :red
end